### ISSUE TITLE
Use all regexes as features for CRF

### ISSUE THREAD

**Issue by tmbo** [RasaHQ/rasa_nlu#1128]
Right now, we only check if one of the regexes match, but not necessarily which of them. It would be better to have a feature for every one of the regexes.

The `rasa_nlu.extractors.crf_entity_extractor.py` should be extended to add these features and use them for the prediction.

**Comment by twhughes** [comment]
Would you give some feedback on how you would like to format the new features?

Currently, if the user specifies two regexes (for example), then for a given word in the training set, the feature dictionary will contain 

`{'0:pattern': 'N/A'}`
for the case that neither regex is matched
`{'0:pattern': '0'}`
for the case that only first regex is matched
`{'0:pattern': '1'}` 
for the case that only second regex is matched, and
`{'0:pattern': '0'}`
for the case that both regexes are matched (I am assuming).

For this issue, would you like it to return something like
`{'0:pattern_0': 'N/A', '0:pattern_1': 'N/A'}`
`{'0:pattern_0': '0', '0:pattern_1': 'N/A'}`
`{'0:pattern_0': 'N/A', '0:pattern_1': '0'}`
`{'0:pattern_0': '0', '0:pattern_1': '0'}`
 for these four cases, respectively?

Would you like me to follow any specific naming convention for the feature key? or the corresponding value?

Also, how should the it handle the case where a certain regex does not match any of the words in the training set?

Thanks

**Comment by tmbo** [comment]
If I remember correctly, the regex patterns have a name. So would be good to use that, e.g. `"0:pattern_number"` & `"0:pattern_email"`.

> For this issue, would you like it to return something like
{'0:pattern_0': 'N/A', '0:pattern_1': 'N/A'}
{'0:pattern_0': '0', '0:pattern_1': 'N/A'}
{'0:pattern_0': 'N/A', '0:pattern_1': '0'}
{'0:pattern_0': '0', '0:pattern_1': '0'}
for these four cases, respectively?

sounds good :+1:

> Also, how should the it handle the case where a certain regex does not match any of the words in the training set?

I don't think we need to handle that separately. For all examples, all the regex features will be set to `N/A`, which should mean that the CRF doesn't take them into account.

**Comment by twhughes** [comment]
Ok, I have this implemented now.  However, there were a few complications and it required changing the `RegexFeaturizer` class a bit.

The main issue was that I was not sure how to pass the `known_patterns` attribute of the `RegexFeaturizer` to the `CRFEntityExtractor` so that I could see the names of the regexes when constructing features.  I would have assumed this was done by passing it through the `message` objects but it did not seem like an option here.

I found a workaround with this line: 

`known_patterns = self.partial_processing_pipeline[-1].known_patterns`

Which just looks at the previous component in the pipeline, but I know this is a hack and is not going to be robust to changes in the pipeline.

Perhaps at some point could you explain to me the best way to pass these variables between components?

Thanks
