### ISSUE TITLE
remove `/config` endpoint

### ISSUE THREAD

**Issue by amn41** [RasaHQ/rasa_nlu#1132]
suggest to remove this endpoint since it has no real use

**Comment by wrathagom** [comment]
why not add a `?project=` parameter to it and re-purpose it for fetching configs of specific projects? We don't use it to my knowledge so fine with getting rid of it... just a thought.

**Comment by AnwarKD** [comment]
It's used for example by RASA UI which fetch the config for training a new NLU model from  '/config' endpoint.

**Comment by akelad** [comment]
@AnwarKD i'm afraid that's not a product we maintain

**Comment by tmbo** [comment]
This endpoint is already removed (#1482) - the reason is conceptual: it assumes the server has some model config always available, but actually it has not and should not (as the config is not needed to start the server as it is only needed to train a model. e.g. if you just want to serve models, you do not need a separate config). instead we want users to supply the config as part of the train request. I think there might be a use for an endpoint to e.g. get the config of a specific model or something like this for e.g. Rasa UI to pull and show
