### ISSUE TITLE
Supporting Entity Roles

### ISSUE THREAD

**Issue by 91ns** [RasaHQ/rasa_nlu#1169]
Hello, 
I need to know if there's a plan to support Entity Roles in Rasa NLU, if not I will work on my own solution and maybe push it if it works well. So I could use some feedback on this issue.

**Comment by amn41** [comment]
Thanks for creating the issue and exciting that you're interested in working on it. What use cases do you have for them specifically? Location:origin and location:destination would be an obvious one, any others?

**Comment by NourShalabi** [comment]
Ideally, one should be able to assign as many custom roles as possible, because different words can refer to/be in relation with different things within a specific domain. 

Here are a few cases. I will add more soon. 

"I'm looking for an **Italian** restaurant"
nationality:cuisine
 
"What are the US visa requirements if I'm **Italian**?"
nationality:citizenship

"What are the entrance fees to Turkey for an **American**"
nationality:citizenship

"I want to open a **savings** account with **500** USD, then transfer **1000** USD from my **current** to my **savings** account" 
account:open_type
money:initial_amount
money:transfer_amount
account:transfer_from 
account:transfer_to

In one thread a suggestion was made to assign the named entity with "role:destination" as the name of the entity, I tried that but it naturally failed, because it will recognize the word as "role:destination" regardless of it's position/context in the sentence.

**Comment by jekirl** [comment]
Was there any further work done on this/did you already get it working @91ns

**Comment by akelad** [comment]
for the moment we've not been looking into this, no.

**Comment by dansheme** [comment]
@91ns I was wondering if you found some sort of solution or workaround for this. I have a similar use case where entity roles could be extremely helpful. Thanks!

**Comment by amn41** [comment]
@dansheme are you willing to share the use case?

**Comment by dansheme** [comment]
Yes, of course @amn41 . Take the following sentence for instance: "John called mom". I can identify two entities, "John" and "mom" and I can identify that the intent is "phone_call_was_made" but I would like "John" to have the role "caller" and "mom" to have the role "callee".
I guess there are other ways to look at it like relations between entities, so "John" might have an attribute called "callee" that equals to "mom".

**Comment by amn41** [comment]
understood, is that what you're building? I'm just curious about real-world cases where people need this.

**Comment by dansheme** [comment]
No, not really. My use case is more related for understanding technical documents. I don't have much more information to share at the moment but I will post it here when I do.

**Comment by tahamr83** [comment]
@amn41 So one thing that we encountered while building a demo ordering bot was when someone wanted to change their order. They could say 
"Can you change the Big Mac with a Cheeseburger" 
alternatively 
"Can I have a Cheeseburger instead of the Big Mac"

So I think entity roles fit in this use case.

**Comment by amn41** [comment]
thanks! we're working on a feature that would enable this + composite entities
