### ISSUE TITLE
Rasa NLU imbalancing and Features

### ISSUE THREAD

**Issue by samho1028** [RasaHQ/rasa_nlu#1188]
**Rasa NLU version**:

**Operating system** (windows, osx, ...):

**Content of model configuration file**:
```yml

```

**Issue**:
 How do I set the yaml file so that it runs spacy_scikit while performing balancing. In addition, I also would like to add negation features (e.g. not, never, no) in the pipeline. 

also, is it necessary to factor in balancing when running the tensorflow_embedding pipeline?

Thank you for your help

**Comment by amn41** [comment]
Usually imbalance happens because you have a lot of examples of one intent, where you really only want to train the entities. In the `json` format, you can simply leave out the `intent` field and these won't be used to train the intent classifier. 

If you want to do anything more sophisticated you'll have to write code (e.g. subclass a classifier), that's not something you can do in config

**Comment by samho1028** [comment]
Hello Thanks for the answer,

Regarding the balancing issue (for intent classification), is there a rule of thumb when it comes to finding the optimal distribution for each of the categories? 

Would increasing the number of records of one category reduce the accuracy of another? 

thank you

**Comment by amn41** [comment]
that's a very broad ML question :) 
please post it in the [forum](https://forum.rasa.com) - there will be many users who can share their experience
