### ISSUE TITLE
FastText with ner_crf

### ISSUE THREAD

**Issue by ctrado18** [RasaHQ/rasa_nlu#1215]
Since this https://github.com/RasaHQ/rasa_nlu/issues/869 is closed. What extaclty I have to do when I want to use fastText word vector together with ner_crf? Do you really have to train the spacy POS tagger or just add this tagger? The process for packaging the fastText vector seems ok, but what about this tagger issue? To train a POS Tagger seems a bit not appropriate. Is it possible to just replace the fastText vectors within the spacy word vectors?

**Comment by akelad** [comment]
I guess as @znat suggested you can download an already trained model and just replace the word vectors with the fasttext ones? Or were you having issues with that?
Aside from that, I'm wondering if you've tried using the tensorflow_embedding pipeline for entity extraction? 
And if that didn't work, an easy option might be downgrading spacy to 1.9.x and using the german model from there, because that is a lot better :)

**Comment by ctrado18** [comment]
Your are confusing me more.

> I guess as @znat suggested you can download an already trained model and just replace the word vectors with the fasttext ones? Or were you having issues with that?

Yeah but how I do that? Just copy the .vec file to the spacy model folder? There are many different information out there like this: https://spacy.io/usage/vectors-similarity#converting
What does "replacing" mean?

> Aside from that, I'm wondering if you've tried using the tensorflow_embedding pipeline for entity extraction?

Is this possible now? I haven't read this in the docs... I thought tensorflow_embedding  is just for intent. Very confusing. That's I wrote somewhere else. The docs should be somehow more used to update new infos like usage of fastText. It is now very confusing. :smile:

When I get FastText ready and afterwards maybe I will downgrade, but it seems very well?

**Comment by akelad** [comment]
About copying vectors over - honestly i'm not sure, i've never done this myself. @znat do you have any advice?

Yes, entity extraction is possible with the master version of core! you just need to switch the docs to the appropriate branch: https://nlu.rasa.com/master/pipeline.html#tensorflow-embedding 😄

**Comment by ctrado18** [comment]
I am still wondering about the entity extraction with tensoflow embedding . 😄 I switsched to master in the docs. And in doc changes there is nothing about that?

**Comment by akelad** [comment]
Changes are listed here - https://nlu.rasa.com/master/changelog.html#unreleased-0-13-0-ax-master
And you can see more about entity extraction with tensorflow here: https://nlu.rasa.com/master/pipeline.html#tensorflow-embedding

**Comment by akelad** [comment]
Oh sorry I posted that link previously - `ner_crf` is now included in the standard pipeline called "tensorflow_embedding". You can also just add the relevant components to your current config file:
```
- name: "tokenizer_whitespace"
- name: "ner_crf"
```

**Comment by ctrado18** [comment]
For me, there is nothing with entity extraction within https://nlu.rasa.com/master/pipeline.html#tensorflow-embedding.

Still there you use the `language`. But for new version, you don't need that anymore when you use ner_crf with tokenize_whitespace, right?  This is due the PR for ner_crf without spacy? Maybe this should be to the docs.

When you use

```
- name: "tokenizer_whitespace"
- name: "ner_crf"
```
then, ner_crf doesn't use POS Tags anymore, right? 

The confusion came because you said you can do entity extraction with trensorflow embeding, but that not the case since it still uses CRF. I thought you did in a more fancy deep learning sequential way with tensorflow embedding. So I think this formulation is quite confusing?

**Comment by akelad** [comment]
that's strange - can you not see this part of the docs from the link you just posted?
![screen shot 2018-07-18 at 10 44 01](https://user-images.githubusercontent.com/32450038/42870232-8d815e4c-8a77-11e8-8fce-0c61107d8d63.png)

Yes we still have a language parameter, but this is just there so you can keep track of which bot this config file is for - it's not used in any way. 

Yes, `ner_crf` does not use POS tags anymore - we ran some evaluation and saw no performance decrease.  

So the point is, language agnostic entity extraction is now possible - which is part of the idea of the `tensorflow_embedding` pipeline, that's why we include it there. Trust me, the fancy deep learning methods just take a lot longer to train and don't show much improvement if any so far 😄

**Comment by ctrado18** [comment]
> Yes we still have a language parameter, but this is just there so you can keep track of which bot this config file is for - it's not used in any way.

So this is just like a comment. This has no impact when you use tokenizer_whitespace. But when you use the spacy tokenizer together with ner_crf it uses spacy and you need language code? And that new interplay should be commented in the docs - there is no remark to language agnostic entity extraction

> So the point is, language agnostic entity extraction is now possible - which is part of the idea of the tensorflow_embedding pipeline, that's why we include it there. Trust me, the fancy deep learning methods just take a lot longer to train and don't show much improvement if any so far 😄

Thaank you for this insight. 😄

**Comment by akelad** [comment]
Yes good point about the docs, I'll make a note of it and we'll add it! For spacy you need either the language paramter yes, or the model parameter as a part of nlp_spacy. 

If you have no more questions for now, can we close this issue?
