### ISSUE TITLE
featurizer_count_vectors with words and N-Grams?

### ISSUE THREAD

**Issue by ctrado18** [RasaHQ/rasa_nlu#1217]
Hey,

I need to use N-Grams with featurizer_count_vectors , but I think it would improve importantly the classification if you could also use it together with word itself. Such that not trained words like for the tensorflow_embedding have a chance if they have specific ngrams. 

Can you this easily within the pipelin or is just one possible at the moment?

```
pipeline:
- name: "intent_featurizer_count_vectors"
  analyzer: 'char'
  "min_ngram": 2  # int
  "max_ngram": 3  # int
```

Can you put the featurizer as a series, such that first it creates features with words then you put again in the pipeline the featurizer for `char`?

```
pipeline:
- name: "intent_featurizer_count_vectors"
  analyzer: 'char'
  "min_ngram": 2  # int
  "max_ngram": 3  # int
- name: "intent_featurizer_count_vectors"
  analyzer: 'word'

```

EDIT:

I tried the `intent_featurizer_ngrams` after `intent_featurizer_count_vectors` in my pipeline:

```
language: "de_core_news_sm"

pipeline:
- name: "nlp_spacy"
- name: "tokenizer_spacy"
- name: "intent_featurizer_count_vectors"
- name: "intent_featurizer_ngrams"
  # Maximum number of ngrams to use when augmenting
  # feature vectors with character ngrams
  max_number_of_ngrams: 5
- name: "intent_classifier_sklearn"
```
But this gives error:

```
Traceback (most recent call last):
  File "C:\Users\\Anaconda3\envs\rasa12\lib\site-packages\rasa_nlu\model.py", line 340, in parse
    component.process(message, **self.context)
  File "C:\Users\\Anaconda3\envs\rasa12\lib\site-packages\rasa_nlu\featurizers\ngram_featurizer.py", line 88, in process
    updated = self._text_features_with_ngrams(message, self.best_num_ngrams)
  File "C:\Users\\Anaconda3\envs\rasa12\lib\site-packages\rasa_nlu\featurizers\ngram_featurizer.py", line 97, in _text_features_with_ngrams
    return self._combine_with_existing_text_features(message, extras)
  File "C:\Users\\Anaconda3\envs\rasa12\lib\site-packages\rasa_nlu\featurizers\__init__.py", line 18, in _combine_with_existing_text_features
    additional_features))
  File "C:\Users\Anaconda3\envs\rasa12\lib\site-packages\numpy\core\shape_base.py", line 288, in hstack
    return _nx.concatenate(arrs, 1)
ValueError: all the input arrays must have same number of dimensions
```

**Comment by Ghostvv** [comment]
Right now, `analyzer` cannot be passed through pipeline, in order to use `char` you'll have to subclass  `intent_featurizer_count_vectors` and overwrite its `train` method: https://github.com/RasaHQ/rasa_nlu/blob/c64991fd30e4ad35246ff82ec19e67f1deb724b3/rasa_nlu/featurizers/count_vectors_featurizer.py#L186 to pass custom `analyzer` directly to `CountVectorizer`

`I tried the intent_featurizer_ngrams after intent_featurizer_count_vectors in my pipeline` - what version of `rasa_nlu` do you use? It was fixed in latest `master`.

**Comment by ctrado18** [comment]
Thank you! I use 12.3 But I think I try the master. Would it be enough to add `anaylzer` in

```
self.vect = CountVectorizer(token_pattern=self.token_pattern,
                                    strip_accents=self.strip_accents,
                                    lowercase=self.lowercase,
                                    stop_words=self.stop_words,
                                   analyzer='char'
                                    ngram_range=(self.min_ngram,
                                                 self.max_ngram),
                                    max_df=self.max_df,
                                    min_df=self.min_df,
                                    max_features=self.max_features,
                                    tokenizer=self._tokenizer)

```

**Comment by JhansiA** [comment]
Am also getting the same error, can anyone has correct answer?

**Comment by amn41** [comment]
this should be possible, either by subclassing the countvectorfeaturizer or by having two copies in series as you suggest. You could do that by creating a [custom component](http://rasa.com/docs/nlu/customcomponents/) that uses the 'char' analyser (just make sure to give it a different name from the default) I'd be curious to hear how this goes! 

The error you post does seem like a bug, because the whole point of the `_combine_with_existing_text_features` method is to combine arrays of different sizes

**Comment by jamesmf** [comment]
I had some success with this, and it'd be a great feature to have available via config rather than custom component!

Would it be good to have it as its own separate component? Such that you could specify very different word vs. subword parameters. I assume that would make them both smart about merging text_features with each other, and they could have default parameters that were appropriate (different min/max n_grams, max_vocab).

**Comment by amn41** [comment]
awesome idea! I'd suggest you create an issue and we can discuss there what an implementation would look like 🚀
