### ISSUE TITLE
Incorrectly recognized entity (regex features)

### ISSUE THREAD

**Issue by derdanielb** [RasaHQ/rasa_nlu#1301]
**Rasa NLU version**: 0.12.3

**Operating system**: Windows 10

I trained a chat bot (using rasa core + nlu), which works well for all trained intents yet. I defined to recognize a 'target' entity by using regex_features. Somehow the 'greet' intent manages to recognize the regex expression, which is obviously not matched there.

My training data looks like this:

`{  "rasa_nlu_data": {
      "regex_features": [{"name": "target",
      "pattern": "[Aa-Zz]{1}[0-9]{5}"}],
      "entity_synonyms": [],
      "common_examples": [
        {"text": "Hello", "intent": "greet", "entities": []},
        {"text": "Hey", "intent": "greet", "entities": []},
        {"text": "Hallo", "intent": "greet", "entities": []},
        {"text": "Guten Tag", "intent": "greet", "entities": []},
        {"text": "Hi", "intent": "greet", "entities": []},
        ... // other examples for other intents
       ]}`

Triggering the 'greet' intent causes to incorrectly identify the target entity.
Message 'hi' matches the regex expression for a word with a leading char and five trailing numbers, eg. _A12345_:

>  rasa_core.processor  - Received user message 'hi' with intent '{'name': 'greet', 'confidence': 0.9485557225674938}' and entities '[{'start': 0, 'end': 2, 'value': 'hi', 'entity': 'target', 'confidence': 0.7657164175690839, 'extractor': 'ner_crf'}]''

Any ideas why this is happening? Can this be fixed?

**Comment by akelad** [comment]
Thanks for raising this issue, @twhughes will get back to you about it soon.

**Comment by twhughes** [comment]
@derdanielb Could you paste some of the training examples that you have where the `target` entity is defined?  

Also, how are you sure that it's the regex that is matching `hi`?

**Comment by derdanielb** [comment]
I removed the regex from 'regex_features'. 'hi' was still incorrectly identified. Thus, it probably was not caused by the 'regex_features'.

I am having an inform intent, which is trained by multiple random samples of the given regular expression to recognize the 'target' entity (eg. A12345, B84721, ...).
I don't understand why the greet intent was triggered and still an the entity, which is trained on a different intent, is (incorrectly) recognized.

**Comment by twhughes** [comment]
Hm.  I agree it seems strange.  

At least we know it is not the regex that is causing this.  

At this point the only thing I can think of is maybe it thinks that 'hi' is a target entity because it contains only a few characters.  I would recommend playing a bit with the CRF features in your pipeline.  You can read more about that here https://rasa.com/docs/nlu/pipeline/#

I also noticed that the confidence of 'hi' being labeled as a target was somewhat low (0.76).  Hopefully on your real target examples, this is higher.  If so you can choose a threshold for target entities that is > 0.8 or so to filter these out.  http://rasa.com/docs/nlu/master/fallback/#choosing-a-confidence-cutoff
Before this, maybe triple check that there are no issues with your training data (like target entity examples that deviate from your A12345 format).
