### ISSUE TITLE
Feature request : other langages with docker container

### ISSUE THREAD

**Issue by nicolaspernoud** [RasaHQ/rasa_nlu#1364]
Hello,

Would it be possible to add to documentation how to change langage (to french) with the docker container ?

Thanks,

**Comment by akelad** [comment]
You'd have to either modify the dockerfile to download a french model, and build a custom image. Or use the tensorflow image, that should work with french.
Since this is a question, rather than an issue, I'll close this. Please post in the [forum](https://forum.rasa.com) if you have further questions
