### ISSUE TITLE
Improving NLU with model stacking and transfer learning?

### ISSUE THREAD

**Issue by ctrado18** [RasaHQ/rasa_nlu#1572]
Hey,

I might asking what can I do for improving NLU intent results. As you can have imbalances I thought it can be a good idea to do model stacking with the tensorflow_embedding model trained on different data sets?

Or using a spacy model togehter with tensor_embedding? So the model might learn when to use spacy and when to use tensorflow?

Or transfer learning: Using pre trained spacy vectors how can I fine tune this with tensorflow for my data set?

Thanks!

**Comment by wrathagom** [comment]
Since these aren't direct feature requests or bugs, I am going to guess that the Rasa team would prefer they exist in the forums rather than here. Can you re-create this as a post there? forum.rasa.com

I would also include any specific problems you are facing that the current pipelines don't solve.

**Comment by ctrado18** [comment]
I thought it could be an enhancement and how you would using rasa code to implement such things. @Ghostvv ?

**Comment by Ghostvv** [comment]
please create a post in the forum, since it is rather a discussion. Short answer, it is not an easy thing to do currently
