### ISSUE TITLE
rasa in docker - tensorflow error "invalid opcode"

### ISSUE THREAD

**Issue by trstn70** [RasaHQ/rasa_nlu#1639]
I'm using this repository: https://github.com/sasastarcevic/rasa-core-and-nlu-docker-compose

**Rasa NLU version**:
The Repo uses image tag "latest" as it is not defined. The Dockerfile executes "pip install rasa_core". This seems to be the newest Version as of today.

**Operating system**:
Debian 9 VM on Proxmox

**Issue**:
the rasa container is being perodically restartet and i see a tensionflow error in the logs:

```
Jan 23 10:53:39 lxvm165-113 kernel: [ 7357.922165] traps: python[20676] trap invalid opcode ip:7f5368d55250 sp:7ffcd9265c20 error:0
Jan 23 10:53:39 lxvm165-113 kernel: [ 7357.922193]  in libtensorflow_framework.so[7f53688c6000+c88000]
```

**Comment by akelad** [comment]
Thanks for raising this issue, @MetcalfeTom  will get back to you about it soon.

**Comment by MetcalfeTom** [comment]
Hmm this one's a little mysterious, I've been doing some researching and [it seems to be due to an incompatibility between the OS and the tensorflow binary](https://github.com/nodejs/node/issues/3898)

As a first pass at a solution, could you try again using a [different tensorflow binary](https://www.tensorflow.org/install/) (or perhaps even by [compiling one from source](https://www.tensorflow.org/install/source)) and get back to us with your results
