### ISSUE TITLE
Evaluate script gets entity predictions even when no extractors are present

### ISSUE THREAD

**Issue by akelad** [RasaHQ/rasa_nlu#1692]
This line here:
https://github.com/RasaHQ/rasa_nlu/blob/master/rasa_nlu/evaluate.py#L725
should go in the `if extractors:` section:
https://github.com/RasaHQ/rasa_nlu/blob/master/rasa_nlu/evaluate.py#L753

Otherwise it unnecessarily goes through the data twice when no entity extractor is present. 
In general we should think about refactoring this script, it could easily get the entities/intents in one go

**Comment by erohmensing** [comment]
- This specific issue should be fixed via community PR #1763. 
 - Creating a new issue for removing duckling from interpreter (instead of from `extractors` and `entity_predictions`) so that it doesn't call the http server -- I've already implemented this change locally and will either merge it separately or with that community PR. 
 - I think it makes sense for any further efficiency refactoring to be tabled until the merge since there will likely be duplicate code anyway.
