### ISSUE TITLE
Duckling Alternative?

### ISSUE THREAD

**Issue by parthsharma1996** [RasaHQ/rasa_nlu#1711]
`ner_duckling` has been deprecated and `ner_duckling_http` has been introduced since version 0.14. `net_duckling_http` requires the running of a duckling http server, which either requires docker or
haskell. Now, the hosting service(DreamHost shared VPS) we are using for deploying our chatbot neither supports `docker` nor `Haskell`. Hence we are unable to use date/time extraction.

How do I solve this? Is there any alternative to `ner_duckling_http` we can use? 

Currently the only solution I can think of is to use an already existing datetime parser like [dateparser](https://github.com/scrapinghub/dateparser) and write a custom Rasa NLU compnent as a wrapper around it.

**Comment by akelad** [comment]
Thanks for raising this issue, @tmbo  will get back to you about it soon.

**Comment by tmbo** [comment]
We needed to remove the ner_duckling component because it was using the old clojure version of duckling that has been deprecated for over a year and doesn't receive improvements anymore. 

I didn't look into alternatives for the date time parsing for a while, so there might be alternatives out there that are easy to integrate, but yes in terms of an alternative the best path forward would be to create a custom component.

**Comment by parthsharma1996** [comment]
Okay, I will write a custom component using https://github.com/scrapinghub/dateparser . Although it doesn't seem to be as advanced as duckling in terms cases covered and features. 

e.g It is unable to parse "the day after tomorrow at noon"

**Comment by mauricedoepke** [comment]
Implementing  a foreign function interface for duckling eould probably be the cleanest solution.

This would need a few lines of python, a few more of haskell. And a whole research team to force ghc compiling it.

**Comment by akelad** [comment]
i'm going to close this then as the question was answered
