### ISSUE TITLE
accurate intent not recognize

### ISSUE THREAD

**Issue by surendra3584** [RasaHQ/rasa_nlu#1774]
i have intent in nlu.md file like these

## intent: queryprepaid1
- time taken to switch prepaid to postpaid?

##intent: querypostpaid1
- time taken to switch postpaid to prepaid?

there is a different intent but after run these implemented same action for both intent,why?
please help me out.

**Comment by akelad** [comment]
if you only have one example per intent the model won't be able to accurately recognise the intents. Also, this looks like you should use entities to distinguish between user inputs rather than intents :) 
I'm going to close this because it's more of a usage question than an issue, please post in our [forum](https://forum.rasa.com) if you have any further questions
