### ISSUE TITLE
How to connect Database to rasa core?

### ISSUE THREAD

**Issue by GAkushshah** [RasaHQ/rasa_nlu#2266]
## How to connect Database to rasa core?
Want to fetch data from the database as per the query defined in the action.

**Comment by josue7** [comment]
I don’t think this is really Rasa-related since you can use pymysql (for MySQL obviously :smiley:) & others, or an ORM such as SQLAlchemy to do this. For example, for returning the first name of a person in a database from an “ID” entity, things could look like this:

def read(id_person: int) -> Person:
    db = pymysql.connect(SERVER, USER, PASSWORD, DB)
    cursor = db.cursor()
    sql = "SELECT * FROM PERSON WHERE ID = '%d'" % (id_person)
    try:
        cursor.execute(sql)
        results = cursor.fetchall()
        for row in results:
            first_name = row[1]
            last_name = row[2]
            age = row[3]
            sex = row[4]
            income = row[5]
            person = Person(id_person, first_name, last_name, age, sex, income)
    except:
        print("Error fetching data.")
    finally:
        db.close()
    return person

If the ID is in a slot, you can easily pass it to the read function using the tracker.get_slot function and then get the person object in return. Then using the dispatcher you could simply pass person.first_name in the response.
