### ISSUE TITLE
Evaluating the performance of a pipeline

### ISSUE THREAD

**Issue by ajayrfhp** [RasaHQ/rasa_nlu#248]
How to add evaluating models for intent classification as a feature. Where would it fit in the rasa pipeline. Create a new module under rasa_nlu called evaluators  ? Or is there any existing module to which this can be added ?
Here is a hacky version of what I seek to implement. 

```python
import requests
import json
cnt = 0
for x,y in zip(X_test,y_test):
        inp = ' '.join(x)
        d = {'q':inp}
        data = json.dumps(d)
        res = requests.post('http://localhost:5000/parse',data = data)
        if(res.json()['intent'] == y):
                cnt = cnt + 1
print 1.0 * cnt / len(X_test)
```

**Comment by tmbo** [comment]
Yes that sounds good, depending on the amount of code, we might need to extend to a package.

Currently there is no seperate way to evaluate models. There is only train and process. We might think about adding a test methods to the components if needed (depends if you can do all of the evaluation from the "outside"). But it might just as well be enough to process each of the test examples on its own and compare the results. 

Instead of using the http api, I would directly use python code to call the process method.

**Comment by wrathagom** [comment]
@tmbo is this one finished with the evaluate.py functionality?

**Comment by wrathagom** [comment]
I think the evaluate functionality is awesome by now, closing.
