### ISSUE TITLE
What is the purpose of on_new_message and where it is defined. I need to check the source code

### ISSUE THREAD

**Issue by Subhojeetr** [RasaHQ/rasa_nlu#2700]
What is the use of On_new_message . Where is it defined.  I need to know the Source code.
Rasa-core 0.11.12
Python 3.5
OS windows 10

**Comment by SaikiranMitta16** [comment]
This is done when the blueprint is registered for an input channel. The function of agent.handle_message() is given as an argument to channel.blueprint().

It would have been great if the agent object would have been used rather than just the function. It would have given a lot more flexibility in the custom channel.
