### ISSUE TITLE
Add information about training time to documentation 

### ISSUE THREAD

**Issue by alexDeCastroAtGit** [RasaHQ/rasa_nlu#332]
Hi there,
another documentation request/question: 
do you guys have any data on training times for different sizes of data sets? This would be a good benchmark for all newcomers. 

Perhaps another documentation feature? 

Many thanks,
Alex

E.g.: 
On a OSX (3.1 GHz Intel Core i7 ; 16 GB 1867 MHz DDR3) it's taking me about 2.15 hours to train a new model on data set of 100 requests. 

 

**rasa NLU version** (e.g. `0.7.3`):

**Used backend / pipeline** (`mitie`, `spacy_sklearn`, ...):

**Operating system** (windows, osx, ...):

**Issue**:

**Content of configuration file** (if used & relevant):
```json

```

**Comment by xliuhw** [comment]
I strongly agree this will be very useful!

Currently I am using mitie for entity extraction which is extremely slow. The train has been running for two days now. The problem is there is no progress output from the latest version. It just show:
num training samples: 9471
then stopped then.
I have no idea how long it will take / when it will finish or crash.

Thanks!

**Comment by wrathagom** [comment]
I am going to consolidate this one in with #621
