### ISSUE TITLE
How to preprocess utterances?

### ISSUE THREAD

**Issue by znat** [RasaHQ/rasa_nlu#360]
**rasa NLU version** :`0.8.5`

I would like to preprocess utterances (remove accents, punctuation, lowercase)
Can that be done by prepending the pipeline with a new component? The doc mentions the training pass but not the predicting one. 

Would utterances at predicting time be preprocessed as well?

**Comment by twerkmeister** [comment]
As of now this is not easily possible. The components are trained one by one and not in an end-to-end fashion. Thus, adding a component that alters the text only alters the text during processing, not during training. For now, you would have to alter your training data and input to rasa nlu in your own application logic. I see merit to your approach since it would allow people to iterate and do standard tasks more quickly. We'll discuss this middle ware approach during our next meeting

**Comment by znat** [comment]
I see. Just to clarify, preprocessing would need to happen during training and predicting.
Do you want me to close the issue or do you want to move it in your discussion pipeline?

**Comment by tmbo** [comment]
Right, so you need to do the same preprocessing during the training of the model as well as during prediction time. Otherwise the models performance might degrade due to a difference in the data between train and processing.

**Comment by nkrot** [comment]
I also find it useful if data could be processed consistently both at training stage and at prediction stage (the latter seems to be called `processing` in this thread). Has it been implemented in a version of `rasa_core` and `rasa_nlu`? From the documentation on rasa nlu 0.12.3 (section about pipelines) it seems that the pipeline only affects incoming messages, that is, only works at prediction stage, and not at training stage, but I may be wrong, have not read the whole documentation thouroughly-5-times. Please comment on whether the same processing is already applied to training data and incoming messages.
thank you very much
