### ISSUE TITLE
Configuration file name confusion in docs tutorial

### ISSUE THREAD

**Issue by tmbo** [RasaHQ/rasa_nlu#401]
Sometimes we are talking about `config.json` but we are using `config_spacy.json`. That should be clarified.

**Comment by PHLF** [comment]
I would like to think that defining the name of the config file with the `config` parameter in the config file is by itself confusing. And having a separate app.json file doesn't really help much either 😉

**Comment by Le-Fix** [comment]
**This is closely related to #610 since the config file is used for different purposes.**

Sometimes it really makes sense to call it config_spacy.json because it can be changed to some other config_mitie.json because the paths are set elsewhere (cli arguments e.g)
Elsewhere a name like config_spacy.json doesn't make sense since it contains parameters which go far beyond pipeline/model setup

I propose closing this issue in favor of #610 because it's the underlying problem.
