### ISSUE TITLE
multiple entity recognition

### ISSUE THREAD

**Issue by atkins1** [RasaHQ/rasa_nlu#427]
**rasa NLU version** (`0.9.0a1`):

**Used backend / pipeline** (`spacy_sklearn`):

**Operating system** (windows):

**Issue**: Unable to recognize multiple entities in the query, for Ex: is there any **eligibility** to **apply** for higher education ? 

Eligibility and apply are my custom entities, the model was trained on eligibility, apply as entities and are not occurring together in any sentence of the training data. 

I want to understand is it just that sentences of training data should have multiple entities and that is why multiple entities are not being recognised ? If that is the case should the training data contain all possible combination of entities ?

```json

```

**Comment by tmbo** [comment]
So the model is trained to recognize certain sentence structures. E.g. the sentence structure for "Can I **apply** for higher eduction?" is quite different compared to "is there any **eligibility** to **apply** for higher education?". Hence, it is not so important to include all possible combinations but rather focus on the different sentence structures that are possible.

**Comment by tmundt** [comment]
May I step in to ask the following:
How does training in means of NER occur in detail? I suppose there should be a set of sentences/phrases whose features (like words) are extracted  to be then compared to a data knowledge base. If there is a match, the feature got labeled and therefor identified as entity, right?

I learnt I do not need a frontend for training NER, right? It is all about REST AFAIK.

BTW: Good job guys, that you build up RASA as alternative to other AI frameworks, preventing usage of (our) data behind the scenes! 👍

**Comment by tmbo** [comment]
How the training happens in detail depends on the used classification model. So let's say we are looking at the `ner_crf` component which uses a conditional random field for the recognition. 

Each sentence in the training data gets featurized - e.g. the context of the labeled entity is converted to a structured representation that contains features indicating
- is the entity capitalized
- part of speech tags of the surrounding words
- last three characters of the word
- ...

All these features aim to capture the context within the entity was observed. The idea is, that instead of directly remembering the entity itself, the model learns to recognize the context and hence is able to find entities that it hasn't seen during training. Hence, a word occurring in the same context as an entity did during training will be labeled with the entities type, even if we haven't seen that word before.

**Comment by wrathagom** [comment]
@atkins1 and @tmundt I'm closing, but let us know if you still have more questions, or join us on [Gitter](https://gitter.im/RasaHQ/rasa_nlu) for more discussion.
