### ISSUE TITLE
Mitie : Additional Output Parameters from Parsed Result

### ISSUE THREAD

**Issue by thilagaDas** [RasaHQ/rasa_nlu#470]
**rasa NLU version** (e.g. `0.8`):

**Used backend / pipeline** (`mitie`):

**Operating system** (ubuntu):

**Issue**:
Unable to add new parameters in the Result Set. I would like to get the **orignial text**(the one in the training set) which is matched with user Text while classifying the intent. curently it is parsing and returning only the intent name and Score. please let me know, with addition to that, how can i get the matched original text?
### Sample Training Set:
        "intent": "greet",
        "entities": [],
        "text": "Hi hello how are you" 

### Expected Result:  
If the search text is **how are you**. 
{
        "_text": "how are you",
        "confidence": 0.4794813722432127,
        "entities": {},
        "intent": "greet",
        **"matched_text": "Hi hello how are you"**
    }

**Comment by wrathagom** [comment]
Sorry because of the way the model training works we aren't matching to a specific training example. Rather we are comparing to all training examples in a given intent.

For entities we do process synonyms, which can make NYC, New York City, and New York all return a value of NYC for example. See the documentation here if it helps: http://rasa-nlu.readthedocs.io/en/latest/dataformat.html#entity-synonyms

Assuming it doesn't can you tell us a little bit about why you need the original training text as opposed to just knowing the intent?

**Comment by thilagaDas** [comment]
Some cases RASA returns incorrect intent classification in case of two utterance per intent. Hence, i thought of calculating similarity score of the user search input with the RASA orignial matched text.

Ok fine, Let me handle at backend. Thanks for the response!
