### ISSUE TITLE
Can ner_crf look more than one work backward?

### ISSUE THREAD

**Issue by znat** [RasaHQ/rasa_nlu#482]
Can `ner_crf`look more than one word backward?

Consider this example:
"transfer 100$ from savings account to checking account"

training this with `source_account`and `dest_account` entities will work. However parsing the following sentence will fail:

"transfer 100$ from **my** savings account to **my** checking account"

The model seems to look only at the previous word, "from" or "to" to distinguish `source_account`from `dest_account`. Adding "my" in between fools it. Can the CRF window be expanded, or is it just 3 words [as suggested here](https://github.com/RasaHQ/rasa_nlu/blob/master/rasa_nlu/extractors/crf_entity_extractor.py#L67)?

**Comment by JoeyFaulkner** [comment]
Hi! thanks for your question,

CRFs are Markov models which mean they can only deal with transitions between neighbouring words, which is obviously a limitation but makes the calculation tractable. 

In this particular case would you consider labelling "my savings account" as an entity instead of just "savings account"?

**Comment by znat** [comment]
@JoeyFaulkner Thank you for the explanation! Yes, I thought of using synonyms as a workaround, that's how I reported #481
