### ISSUE TITLE
Unable to make use of default entities such as money,date,time,etc

### ISSUE THREAD

**Issue by gurunathpr** [RasaHQ/rasa_nlu#532]
rasa-NLU version : 0.9.1

Used backend / pipeline: `spacy_sklearn`

OS: Ubuntu 16.04

Issue:
I installed duckling but it isn't getting used even though I am including it in the pipeline stage.Is there something that I am missing?
Thanks!

**Comment by wrathagom** [comment]
You will have to re-train your model after adding duckling in order to use it. Alternatively you can modify the pipeline stored in the metadata.json file in your model folder.

Also make sure you have duckling dimensions set in your config file.

**Comment by gurunathpr** [comment]
@wrathagom Thanks a lot for responding quickly!

- Where is the config file to set duckling dimensions,I am unable to find something relevant in demo-rasa.json file as well as config_spacy.json?

- I tried modifying the pipeline in the metadata.json file (given below) but it is not being shown when I start the rasa-nlu http server.

[metadata.txt](https://github.com/RasaHQ/rasa_nlu/files/1230221/metadata.txt)

**Comment by HansKannsNLP** [comment]
Your config_spacy.json is you config file where you have to add it. These are all the options which can be included there https://rasa-nlu.readthedocs.io/en/latest/config.html

The ner_duckling is part of the pipline which is described more detailed there https://rasa-nlu.readthedocs.io/en/latest/pipeline.html#section-pipeline

You have to restart the Server after changing the config file and after restarting train your models again. If its not working now it is again a good point to restart with your new models. You dont have to change something in the metadatas.

**Comment by wrathagom** [comment]
Changing something in metadata.json prevents you from having to re-train the model, which depending on the model size can be a big win.

@gurunathpr consolidating @HansKannsNLP and my replies:

- Once you've added ner_duckling to your pipeline you will need to restart your server. You will also need to re-train your model so that the model knows to use duckling.
- If your model took a long time to train or you just don't want to re-train you can modify metadata.json to include duckling. I notice that the file you provided is labeled metadata.txt? is that a typo or did you change the file type when you edited it?
- Setting the duckling dimensions is done in the config file you mentioned. You'll need to add a line as described [here](https://rasa-nlu.readthedocs.io/en/latest/config.html#duckling-dimensions)

**Comment by gurunathpr** [comment]
@wrathagom I have just a hundred examples..so it didn't take a lot of time to train.

1. Added ner_duckling to my pipeline and it worked after training.
2. The file I provided is actually in JSON format but I was unable to upload it directly on github...so pasted it in a text file.
Thanks a lot.It worked.
