### ISSUE TITLE
POST /train?name=my_model trains a model, but can't access with /parse or /status

### ISSUE THREAD

**Issue by ramimanna** [RasaHQ/rasa_nlu#546]
**rasa NLU version**:
Bleeding edge / github clone
**Used backend / pipeline** (`mitie`, `spacy_sklearn`, ...):
mitie

**Operating system**:
Linux Ubuntu 16.04
**Issue**:
First I start rasa as a python server:
`python -m rasa_nlu.server -c config_file.json
`
Then I start a node.js server, in which I POST to the rasa server: /train?name=my_model
The model is trained successfully, and can be found in the models directory.

However, POST /parse with an extra model:"my_model" param and GET /status can't access the model.

The docs for /train says "If you want to name your model to be able to use it during parse requests later on, you should pass the name /train?name=my_model". So I was expecting /train to load the model so I could use it immediately without restarting the python server. Is this a bug or am I missing something?

**Content of configuration file** (if used & relevant):
```json
{
  "pipeline": "mitie",
  "path" : "./models",
  "mitie_file": "data/total_word_feature_extractor.dat"
}
```

**Comment by PHLF** [comment]
Strange, because looking at [the corresponding code](https://github.com/RasaHQ/rasa_nlu/blob/master/rasa_nlu/data_router.py#L191) here is what happens. Once the training is done, the model is created but is not loaded in memory. Then comes a parse request. If it specifies a model name (like you did) it'll look for it in memory, if it cannot be found (which is the case after training) it'll load it from the path made of the `path` value in your config file and the model name you specified. So it should work just fine.
What error do you have exactly? Do you wait for the training response from the server before doing a `parse` request?

**Comment by ramimanna** [comment]
Weird indeed. It's working now, although I don't believe I changed anything.
Either way - it seems this is a non-issue. Perhaps it makes more sense to load the model on /train though? Just seems more intuitive, and may help with speed on the first call to /parse if the model is large.

**Comment by PHLF** [comment]
Yep this is part of some [weirdo's PR](https://github.com/RasaHQ/rasa_nlu/pull/449)

**Comment by ramimanna** [comment]
thanks :)
