### ISSUE TITLE
Mitie : Entities must span whole tokens , Tokenization is not happening properly.

### ISSUE THREAD

**Issue by mayankg53** [RasaHQ/rasa_nlu#554]
In text **100$**  , I can't tag 100 as price and $ as currency in mitie pipeline but it works fine with spacy pipeline, mitie gives error **Entities must span whole tokens** , means mitie tokenizer isn't able to tokenize the string into 100 and $ separately.

I am not able to use different tokenizer in mitie pipeline also, how can we resolve such problems or what can be the best way to tag such kind of text.

**Comment by fakesecret** [comment]
Hello, I already reportd this issue and finished an PR so that Mitie will report a warning instead of errors: https://github.com/RasaHQ/rasa_nlu/pull/531. However, even the updated version will skip your example anyway.

The main conern is still the tokenizer. I suggest to try spaCy tokenizer, that means the pipeline will look like: ["nlp_mitie", "nlp_spacy", "tokenizer_spacy", ...]. As I tested before, spaCy's tokenizer is better than that of Mitie (and of NLTK). I can also confirm that spaCy's tokenizer will correctly separate 100$ while Mitie's cannot. Similar tokenization problems include apostrophes and dots, such as in "I'd 2.5 'Tokens' in 2007."

**Comment by wrathagom** [comment]
What exactly are you trying to accomplish, I assume get the currency as well as value.

Perhaps rather than changing the tokenization the best approach is just to identify `$100` as a currency value and post-process it to get the amount and currency type?

Another option would be to use the regex featurizer to extract currency identifiers into their own token http://rasa-nlu.readthedocs.io/en/latest/pipeline.html#intent-entity-featurizer-regex but this would also require using ner_crf instead of ner-mitie.
