### ISSUE TITLE
I have a requirement to create multiple regular expression for a single entity:"job_name"

### ISSUE THREAD

**Issue by arunchunai** [RasaHQ/rasa_nlu#613]
**Rasa NLU version** (e.g. `0.7.3`):

**Used backend / pipeline** (`spacy_sklearn`):

**Operating system** (linux):

**Issue**:  I have a requirement to create multiple [say 50] regular expression for a single entity: "job_name"

May I know the syntax to declare it. I am trying as below, not sure if it is right?

"regex_features": [ 
{ "name": "jobName1", "entity": "job_name", "pattern": "AED[0-9]" }, { "name": "jobName2", "entity": "job_name", "pattern": "BEDR[0-9]" },
{ "name": "jobName3", "entity": "job_name", "pattern": "CAD[0-9]" },
{ "name": "jobName4", "entity": "job_name", "pattern": "XXMDT[0-9]" },
{ "name": "jobName4", "entity": "job_name", "pattern": "FBC[A-Z0-9]" },
.
.
.
]

**Comment by wrathagom** [comment]
This is covered in the docs here: http://rasa-nlu.readthedocs.io/en/latest/dataformat.html#regular-expression-features

You define just a name and pattern under `regex_features` then you define the entities under `common_examples`

I am uncertain if Rasa will be able to match a **specific** job name as an entity. I think you would have better luck just letting Rasa detect that it **is** a job_name and then using backend code to further classify which job name it is. especially since they are so easily identified by prefix.

Let me know if you still have more questions.
