### ISSUE TITLE
How to update trained model without restart rasa nlu server?

### ISSUE THREAD

**Issue by sagardevadakar** [RasaHQ/rasa_nlu#808]
**Rasa NLU version** : 0.10.4

**Used backend / pipeline** : spacy_sklearn`

**Operating system** : linux

**Issue**: I want to update trained model without restart rasa nlu (0.10.4) server so that it will start referring new trained model. 

**Content of configuration file** (if used & relevant):
```json

```

**Comment by PHLF** [comment]
The default behaviour (as for now) is to use the latest trained model for a project.

https://github.com/RasaHQ/rasa_nlu/blob/bf9a04a8238c80e902dafbebb8c79468471090aa/rasa_nlu/project.py#L59-L64

**Comment by wrathagom** [comment]
To extend @PHLF's excellent answer, you cannot update a model currently. However the default functionality within a project is to train a new model and always server the latest. For more information see the docs here: https://rasa-nlu.readthedocs.io/en/latest/http.html#

Also since you've opened several issues with general questions, I'll invite you to join us on the Gitter where we can answer simple questions quicker. https://gitter.im/RasaHQ/rasa_core
