### ISSUE TITLE
Integrate DialogFlow data to RASA

### ISSUE THREAD

**Issue by gnaazr95** [RasaHQ/rasa_nlu#842]
I have a DialogFlow project that I am trying to import to RASA. I exported the Zip and have a directory set up similar to rasa_nlu/tree/master/data/examples/dialogflow. The docs say to attach this path when making the HTTP request but I'm a little confused as to where exactly I should include this path? I tried doing something similar to curl 'path/to/directory' | \
curl --request POST --header 'content-type: application/json' -d@- --url 'localhost:5000/train?project=test_model&pipeline=keyword' but that didn't work. Any clarifications would be much appreciated.

**Comment by twerkmeister** [comment]
Hey @gnaazr95 the train endpoint accepts training data as a string, writes it to disk and then trains a model based on this training data. Since dialogflow data is split into multiple files, posting it as a training data string won't work. 

You can train your model from the command line with your dialogflow data directory as the data config variable. Afterwards you start the server and send requests to it. Training and using your model: https://rasa-nlu.readthedocs.io/en/latest/tutorial.html#training-a-new-model-for-your-project

**Comment by wrathagom** [comment]
@gnaazr95 let us know if that didn't answer your question.

**Comment by gnaazr95** [comment]
Got it, thanks!
