### ISSUE TITLE
Long response time when querying

### ISSUE THREAD

**Issue by nggary** [RasaHQ/rasa_nlu#860]
Rasa NLU version (0.11.3):

Used backend / pipeline (spacy_sklearn):

Operating system (osx):

I found that the first query after I start the server will take so long, it take about 40 second to load the response, then the query after first one takes 0.5 second, is it normal? Any way to prevent long querying time?

**Comment by wrathagom** [comment]
What you are experiencing is the model being loaded into memory. Obviously this must happen in order for things to work well. Since there is now way around this, you should think of ways to mitigate it's impact. For example if you are serving requests in a. production environment using Rasa then you could pre-load the models on startup by calling `/parse` for each model you want loaded.

Let me know if that doesn't answer your question.

**Comment by wrathagom** [comment]
Not with current offerings, but all it takes to warm up the server is a curl to `/parse` for your model.

@amn41 @tmbo want to add a configuration parameter to load the default model or a model on startup?

**Comment by tmbo** [comment]
Mhm I mean we can do that but I am not sure it has any benefit over doing a request to `/parse`. @nggary what is your use case, why do you need it?

**Comment by wrathagom** [comment]
Closing for lack of movement/discussion. Happy to re-open if it comes back up.

**Comment by RitwikGopi** [comment]
I was able to do this. Currently am accepting a cmd line argument as boolean and if it is true loading all the available projects in the path mentioned. I am thinking we could also change it in such a way to auto load all models or some specified models. Let me know the thoughts on this.

**Comment by yousrahmoh** [comment]
@wrathagom can you explain more on what you mean by _calling `/parse` for each model you want loaded_?
