### ISSUE TITLE
Entity synonyms with verbs

### ISSUE THREAD

**Issue by ctrado18** [RasaHQ/rasa_nlu#967]
Hey,

I use ner_crf and german as language. In german you have a variety of possible verb forms and I try to map sentence like my "glass is broken" to an entity synonym value "defect".

```
`{
    "rasa_nlu_data": {
        "common_examples": [{
        "text": "Meine Uhr ist gebrochen",
        "intent": "Kosten",
        "entities": [
          {
            "start": 11,
            "end": 30,
            "value": "gebrochen",
            "entity": "produkt"
          }],
        "regex_features" : [],
        "entity_synonyms":{
        "value": "defekt
        "synonyms": ["agebrochen", "gebrochen", "kaputt", "rausgebrochen"]
      }
}`
```

The verbs are recognized in the right way but not mapped to the synonym "defekt"! Why? I trained the data with all synonym values. Since the entity is recognized it should be mapped afterwards to the synonym value?
So with the example above the entity in a sentence like "Hilfe, mein Fenster ist gebrochen" is properly recognized but with value "gebrochen" only. So it is not mapped to "defekt".

I wonder how to handle synonyms with verbs. Do I have to put all different verb forms inside the synonym list or just the base form of the verb (here: brechen)?

**Comment by akelad** [comment]
Hi, I'm just wondering if that's directly copied from your training data file? Because there's a few things wrong with it, e.g. missing quotation marks, brackets etc. Also the start and end values are incorrect. Basically it should look like this:

```
{
    "rasa_nlu_data": {
        "common_examples": [
          {
            "text": "Meine Uhr ist gebrochen",
            "intent": "Kosten",
            "entities": [
              {
                "start": 14,
                "end": 23,
                "value": "gebrochen",
                "entity": "produkt"
              }
            ]
          }
        ],
        "regex_features" : [],
        "entity_synonyms": [
          {
            "value": "defekt",
            "synonyms": ["agebrochen", "gebrochen", "kaputt", "rausgebrochen"]
          }
        ]
    }
}
```
Also how many training examples do you have? And can you post what pipeline you've used in your config file? Also in general with labeling entities the markdown format might be easier: https://nlu.rasa.com/dataformat.html?highlight=synonyms#markdown-format

Generally though yes, you do need to add all forms of the word as synonyms

**Comment by ctrado18** [comment]
hey i just wrote i here as an example, no copy. And now it works somehow because I got a typo of a verb in my training data...And I found out that you don't need to put all form of verbs as synonyms? It also recognized "abgebrochenen" though just "abgebrochen" was a synonym.

**Comment by akelad** [comment]
In that case your problem is solved right?
