### ISSUE TITLE
does rasa_nlu support chinese?

### ISSUE THREAD

**Issue by winner484** [RasaHQ/rasa_nlu#975]
does rasa_nlu support chinese?
if not, can it be trained for chinese? if it is possible, can anyone teaches me to do this? 
--great thanks!

**Comment by wrathagom** [comment]
There was some progress on supporting Chinese when Rasa still had a MITIE pipeline component:
https://github.com/RasaHQ/rasa_nlu/pull/477

Some users are trying to tackle it themselves, but it involved training your own spacy model:
https://github.com/RasaHQ/rasa_nlu/issues/705

Since MITIE support has been deprecated we know have to wait/watch for someone to get Chinese working with spacy before it will work with Rasa. Though it looks like it is being pursued by the spacy team:
https://github.com/explosion/spaCy/issues/1523
https://github.com/explosion/spaCy/pull/1210

Let me know if those don't help you get started and we can re-open the issue!

**Comment by akelad** [comment]
just an update: MITIE is getting added back in #980
